name: titova-hw
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - catboost
